### ISSUE TITLE
"like" search results in advanced search for properties with dates are the same as "exactly" 

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#10]
Date: 27.11.2017
Action: 
Advanced search --> Kamingespräche mit Bill Clinton: is like: Date 29.11.2017

Observation: 
There is one input for Kamingespräche on the 28.11.2017 but it won't show in the search of something "like that date". 

Expected result: 
Hits of dates around the chosen date. E.g. I entered the 29.11.2017 for my "like" search. I would expect to also get results for the dates around this date. 
Otherwise, what is the difference between "exactly" and "like" for dates?

**Comment by aapetrova** [comment]
Since PostgreSQL doesn't support a LIKE operator out-of-the-box for date, it's only possible to search by an exact date. A date range picker might be implemented in the future.
For now, I disabled the "like" option for non-text types in order to avoid confusion.
