### ISSUE TITLE
Date of birth input is not like date of birth output (consistency)

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#11]
Date: 27.11.2017
Action: 
Advanced search --> date of birth is exactly: 01.01.0001 (dd/mm/yyyy)--> search 

Observation: 
Result output orders date of birth: yyyy/mm/dd

Expected result: 
Input should be like output.

**Comment by aapetrova** [comment]
yyyy-mm-dd is the HTML5 date specification, while the Mozilla/Chrome date picker uses dd-mm-yyyy. I personally find the year-first format nicer, because chronological sorting is quite straightforward (I think that's why it's standard too).
