### ISSUE TITLE
Advanced Search: Boolean data types can't be selected for search

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#12]
Date: 27.11.2017
Action: 
Advanced Search --> registration is exactly --> 

Observation: 
no option for yes/no OR true/false can be picked. 
There is a plain text field. 
When typing yes/no OR true/false, an error message occurs. 
![image](https://user-images.githubusercontent.com/33317315/33261858-8dd2566e-d364-11e7-8db7-ef595e161a76.png)
![image](https://user-images.githubusercontent.com/33317315/33261867-979c29ea-d364-11e7-9bd2-ccb2815c1a49.png)

Expected result: 
the options of boolean data type should be able to be picked  (some as it works for the date)

**Comment by aapetrova** [comment]
Searching for boolean values is done through a select element now.

**Comment by hofmannc** [comment]
test 30 11.: tested ok, but for re-try in Search-Result list search, the select element is not available
![grafik](https://user-images.githubusercontent.com/14921701/33437587-b66d2cda-d5e8-11e7-8f9c-b0eaf429dd4f.png)
![grafik](https://user-images.githubusercontent.com/14921701/33437597-c04e397e-d5e8-11e7-93ad-f2b58712cfc4.png)
