### ISSUE TITLE
Sending Emails not working

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#15]
Date: 27.11.2017
Action: 
View all members --> select 3 members --> Title: Lore Ipsum, Text: Lore Ipsum --> send
View all members --> select 1 member --> Title: Lore Ipsum, Text: Lore Ipsum --> send

Observation: 
Error message for both versions
![image](https://user-images.githubusercontent.com/33317315/33263762-4497dc38-d36b-11e7-9dd1-35553a1a7971.png)

Expected result: 
Email should be sent to selected users.

**Comment by hofmannc** [comment]
tested 30.11.: Message body is limited again

**Comment by aapetrova** [comment]
Emails work now, but with a delay of about 10 minutes. This happens in other applications as well, so it might be on the mail server side.
