### ISSUE TITLE
Redirecting to "Search results" after editing information not implemented 

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#18]
Date: 27.11.2017
Action: 
view all members --> select one member --> edit --> edit weihnachtsfeier from Barkeeper to Nikolaus --> save 

Observation: 
Change was successfull, but no redirecting to rearch result page. you stay on the editing page. 
When clicking "back" oder using the back arrow, you are right in the editing process from before. 

Expected result: 
after editing the information I expect to redirected to the search result list, I chose the member to begin with.

**Comment by aapetrova** [comment]
"Back to results" button was implemented
