### ISSUE TITLE
"+Add criteria" for batch update not working

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#19]
Date: 27.11.2017
Action: 
view all members --> selecting a few members --> edit selected members --> +add criteria 

Observation: 
Add criteria not working 
![image](https://user-images.githubusercontent.com/33317315/33264974-052c3c92-d370-11e7-8316-5e9a6cb731c6.png)

Expected result: 
Add criteria should add further criteria I want to change for this batch.

**Comment by aapetrova** [comment]
"Add criteria" works now
