### ISSUE TITLE
Unmark of boolean data type not possible 

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#2]
Date: 27.11.2017
Action:
Adding new Member --> Add Information -->  
•	Clicking yes for property “registration” 
•	Trying to unmark. 
(same for: Edit Person Information --> trying to unmark) 
Observation: 
•	No possibility to unmark, once clicked on yes or no. 
![image](https://user-images.githubusercontent.com/33317315/33258362-959f89c6-d359-11e7-9128-17cb2ac81c02.png) 
![image](https://user-images.githubusercontent.com/33317315/33258366-9c24011e-d359-11e7-84df-681f71f3c6ee.png)
Expected result: 
•	It should be possible to redo input. Like this you are forced to chose between yes or no, once (accidently) clicked.

**Comment by aapetrova** [comment]
Added an 'unknown' field (as long as property is not required).

**Comment by hofmannc** [comment]
test date 30.11.: "unknown" field not always displayed and changed selection does not stay

![grafik](https://user-images.githubusercontent.com/14921701/33436919-ab5eecc2-d5e6-11e7-932b-302955be8b30.png)
