### ISSUE TITLE
"Select all" option on "View all member" not available

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#20]
Date: 27.11.2017
Action: 
view all members --> wanting to select all 

Observation: 
--> have to select each individually 
![image](https://user-images.githubusercontent.com/33317315/33265192-f41b52ac-d370-11e7-8a03-cdd75ca4a4b0.png)

Expected result: 
Option for "select all"

**Comment by aapetrova** [comment]
Added "select all" checkbox in the table header.
