### ISSUE TITLE
Incorrect behaviour of Boolean values in Edit page

### ISSUE THREAD

**Issue by aapetrova** [aapetrova/peopledb#25]
Setting boolean values to true or false may turn them into "unknown" after the change is made.
Probably a presentation issue, since the values are correctly saved in the database.

**Comment by hofmannc** [comment]
test date 30.11.: "unknown" field not always displayed and changed selection does not stay

![grafik](https://user-images.githubusercontent.com/14921701/33436919-ab5eecc2-d5e6-11e7-932b-302955be8b30.png)

**Comment by aapetrova** [comment]
"Unknown" is available only if the property is not required. The selected option should be displayed correctly now.
