### ISSUE TITLE
Save and Delete Button “touch” each other

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#3]
Date: 27.11.2017
Action: 
Add New Member --> Salazar, Sara --> Save --> Edit Person Details 
Observation: 
Save and Delete Button touch each other 
![image](https://user-images.githubusercontent.com/33317315/33258600-732b3268-d35a-11e7-8323-6717bcb8ce2d.png)
Expected result: 
A litte gap between those two buttons.

**Comment by aapetrova** [comment]
Adjusted buttons - though they would look better next to each other instead of being stacked: #22.
