### ISSUE TITLE
"E-Mail/ Edit/ Export selected"- Bar on search result list should always be visible (locked)  

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#30]
Date: 04.12.2017
Browser: Chrome 

**Action**: 
Open --> View all members 

**Observation**: 
Given space between each member is really big. 
For very long input like adresses, may be a line break could be used?
![image](https://user-images.githubusercontent.com/33317315/33544489-3c4237de-d8db-11e7-8787-ea09e9b00f0f.png)

**Expected result**: 
Space should be used. Like this a lot of "air" with no content is being built. You have to scroll a lot (downwards and to the right). 
![image](https://user-images.githubusercontent.com/33317315/33544587-a3e8a3a0-d8db-11e7-9142-f7b1345f6e5b.png)
email/edit/export/ bar should be locked to the bottom and always be shown. not only in the end of the scroll list. (imagine a very long list)

**Comment by aapetrova** [comment]
Line breaks were implemented.
