### ISSUE TITLE
Adding new member: not as "required" marked boolean input, still mandatory for saving process

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#31]
Date: 04.12.2017
Browser: Chrome 

Action: 
Add new member --> fill in mandatory fields --> save

Observation: 
![image](https://user-images.githubusercontent.com/33317315/33545443-842fa3a8-d8de-11e7-9128-d8e0ccb5bd6a.png)
though not mandatory, I can't proceed with the saving process unless I fill in fields with a preselection form, though not marked as mandatory. 

Expected result: 
not mandatory fields, should not be needed to be selected.
Works for fields with free text content, and date selection. but not for boolean.

**Comment by aapetrova** [comment]
'Unknown' should serve the purpose of an empty input for non-mandatory fields (it was meant as 'k.A.'), though I guess 'N/A' is a better label.
