### ISSUE TITLE
Advanced search sensitive for names with hyphen

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#34]
Date: 04.12.2017
Browser: Chrome

Action:
Advanced Search --> Family name is exactly --> "möller" (Looking for member "Möller-Batchedited")
(second test: Looking for family name is exactly--> "batchedited" --> same problem --> no results being given)

Observation:
no result is given.
not connected to not using capital letter (tried that out)

Expected result:
Result should not be hyphen sensitive. It should be enough typing the one name of the hyphen connected name.

**Comment by aapetrova** [comment]
I think choosing a partial match would be more appropriate than the exact match in this case.
