### ISSUE TITLE
After creating a new "property group" there is no redirection or button to add "new property"  

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#36]
Date: 04.12.2017
Browser: Chrome

**Action**: 
Creating a new "property group" --> "Geburtstage"

**Observation**:
After creating a new property group nothing further happens or is clickable. 
![image](https://user-images.githubusercontent.com/33317315/33548301-0eb1f91a-d8e7-11e7-85fd-c1ea943d2905.png)

**Expected result:** 
After creating a property group i would like to ad a property to it.
May be add a button that refers directly to the add "property page"
it is unlikely that someone just adds a property group without adding property.

**Comment by aapetrova** [comment]
The option is available in the header.
