### ISSUE TITLE
Adress & Email information are marked yellow during entry process

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#4]
Date 27.11.2017
Action:
+New member --> Fill out Basic Data + Properties --> 
•	Family name *: von Aquin
•	Given name*: Thomas 
•	Address: Feldweg 18 
•	Date of Birth: 01.01.0001 
•	Email: ayanoglu@mpdl.mpg.de 
•	OSD2017 Registered: Yes 
--> Save 
Observation: 
•	Adress and Email is colored yellow while entering information
![image](https://user-images.githubusercontent.com/33317315/33258711-c846307c-d35a-11e7-97b6-fe474c42ad69.png)
Expected result: 
I do not know, why they are yellow.

**Comment by aapetrova** [comment]
Chrome's autofill adds a yellow fill to the input: I don't think this affects design (though admittedly it would look awful if the background were purple for example ;)).
