### ISSUE TITLE
Error message for new member after import

### ISSUE THREAD

**Issue by hofmannc** [aapetrova/peopledb#41]
Date: 12.03.2018

Actions: Import members -> New members are listed -> "+new member" -> enter details -> "save" ->

Observation: 
![pdp_eingabe_new_person_fehlermeldung](https://user-images.githubusercontent.com/14921701/37392809-85341ba0-276f-11e8-956d-23b74df422ea.JPG)

**Comment by aapetrova** [comment]
should be fine now. added an ID column, but another solution might be better in the long term.
