### ISSUE TITLE
Umlaute not shown properly

### ISSUE THREAD

**Issue by melissaMPDL** [aapetrova/peopledb#6]
Date 27.11.2017
Action: 
+ Add new Member:
-  Family Name*: Kierkegaard 
- Given Name: Sören 
- Adress: Am Himmelstor 1
- Date of Birth: 02.02.0002
- Kamingespräch mit Bill Clinton: 28.11.2017
-Registration: no
--> Save

Observation: 
Umlaut "ö" not shown correctly. 
Order of input data not order of output data. (family name comes after kamingespraeche)
![image](https://user-images.githubusercontent.com/33317315/33259370-f956311a-d35c-11e7-9332-1641aa2a9db1.png)

Expected result: 
"ö" should be shown correctly, or there should be a note which says "ö" not possible to use, when adding information. 
Order of input like order of output.

**Comment by aapetrova** [comment]
UTF-8 support should be working now.
